{
 "title": "Thread Pool Playground Dashboard",
 "description": "This dashboard display some basic JVM metrics to see the difference when using various thread pools for the same task to be done.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jvm_cpu_load_process", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "jvm_threads_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "jvm_memory_heap_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_memory_nonheap_used", "legendFormat": "__auto" }
   ]
  }
 ]
}